#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;


namespace NorthwindOpenAccess	
{
	public partial class Territory
	{
		private string _territoryID;
		public virtual string TerritoryID 
		{ 
		    get
		    {
		        return this._territoryID;
		    }
		    set
		    {
		        this._territoryID = value;
		    }
		}
		
		private string _territoryDescription;
		public virtual string TerritoryDescription 
		{ 
		    get
		    {
		        return this._territoryDescription;
		    }
		    set
		    {
		        this._territoryDescription = value;
		    }
		}
		
		private int _regionID;
		public virtual int RegionID 
		{ 
		    get
		    {
		        return this._regionID;
		    }
		    set
		    {
		        this._regionID = value;
		    }
		}
		
		private Region _region;
		public virtual Region Region 
		{ 
		    get
		    {
		        return this._region;
		    }
		    set
		    {
		        this._region = value;
		    }
		}
		
		private IList<Employee> _employees = new List<Employee>();
		public virtual IList<Employee> Employees 
		{ 
		    get
		    {
		        return this._employees;
		    }
		}
		
	}
}
