<%@ Page Language="C#" AutoEventWireup="true" CodeFile="RadGridWithCustomObject.aspx.cs"
Inherits="RadGridWithCustomObject" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head runat="server">
		<title></title>
	</head>
	<body>
		<form id="form1" runat="server">
			<telerik:RadScriptManager ID="RadScriptManager1" runat="server">
				<Scripts>
					<asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.Core.js">
					</asp:ScriptReference>
					<asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQuery.js">
					</asp:ScriptReference>
					<asp:ScriptReference Assembly="Telerik.Web.UI" Name="Telerik.Web.UI.Common.jQueryInclude.js">
					</asp:ScriptReference>
				</Scripts>
			</telerik:RadScriptManager>
			<telerik:RadGrid ID="RadGrid1" runat="server" ShowGroupPanel="true" OnNeedDataSource="RadGrid1_NeedDataSource"
							 OnGroupsChanging="RadGrid1_GroupsChanging" OnDeleteCommand="RadGrid1_DeleteCommand"
							 OnInsertCommand="RadGrid1_InsertCommand" OnUpdateCommand="RadGrid1_UpdateCommand"
							 CellSpacing="0" AllowPaging="True" AutoGenerateEditColumn="True" AutoGenerateColumns="true"
							 AllowCustomPaging="true" AutoGenerateDeleteColumn="true" GridLines="None">
				<MasterTableView AutoGenerateColumns="false" DataKeyNames="CustomerID" CommandItemDisplay="Top">
					<CommandItemSettings ExportToPdfText="Export to PDF"></CommandItemSettings>
					<RowIndicatorColumn Visible="True" FilterControlAltText="Filter RowIndicator column">
						<HeaderStyle Width="20px"></HeaderStyle>
					</RowIndicatorColumn>
					<ExpandCollapseColumn Visible="True" FilterControlAltText="Filter ExpandColumn column">
						<HeaderStyle Width="20px"></HeaderStyle>
					</ExpandCollapseColumn>
					<Columns>
						<telerik:GridBoundColumn DataField="CustomerID" FilterControlAltText="Filter CustomerID column"
												 HeaderText="CustomerID" SortExpression="CustomerID" UniqueName="CustomerID" DataType="System.Int32">
						</telerik:GridBoundColumn>
						<telerik:GridBoundColumn DataField="ContactName" FilterControlAltText="Filter Contact Name column"
												 HeaderText="Contact Name" SortExpression="ContactName" UniqueName="ContactName">
						</telerik:GridBoundColumn>
						<telerik:GridBoundColumn DataField="ContactTitle" FilterControlAltText="Filter Contact Title column"
												 HeaderText="Contact Title" SortExpression="ContactTitle" UniqueName="ContactTitle">
						</telerik:GridBoundColumn>
						<telerik:GridBoundColumn DataField="CompanyName" FilterControlAltText="Filter Company Name column"
												 HeaderText="Company Name" SortExpression="CompanyName" UniqueName="CompanyName">
						</telerik:GridBoundColumn>
					</Columns>
					<EditFormSettings>
						<EditColumn FilterControlAltText="Filter EditCommandColumn column">
						</EditColumn>
					</EditFormSettings>
					<PagerStyle PageSizeControlType="RadComboBox" AlwaysVisible="true"></PagerStyle>
				</MasterTableView>
				<ClientSettings AllowDragToGroup="true">
				</ClientSettings>
				<PagerStyle PageSizeControlType="RadComboBox"></PagerStyle>
				<FilterMenu EnableImageSprites="False">
				</FilterMenu>
			</telerik:RadGrid>
		</form>
	</body>
</html>
